# Generated by Django 3.0.8 on 2020-07-31 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0002_auto_20200731_2313'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomtype',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
