# Generated by Django 3.0.8 on 2020-08-02 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0003_roomtype_thumbnail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='room',
            new_name='room_type',
        ),
        migrations.AddField(
            model_name='reservation',
            name='guest_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
