# Generated by Django 3.0.8 on 2020-08-02 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0005_remove_roomtype_thumbnail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='number_of_rooms',
        ),
    ]
