# Generated by Django 3.0.8 on 2020-08-02 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0006_remove_reservation_number_of_rooms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomtype',
            name='available',
            field=models.IntegerField(null=True),
        ),
    ]
