# Generated by Django 3.0.8 on 2020-08-02 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0008_auto_20200802_2240'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomtype',
            name='image',
            field=models.ImageField(null=True, upload_to='thumbnails'),
        ),
    ]
