# Generated by Django 3.0.8 on 2020-08-03 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0009_roomtype_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='guest_name',
        ),
        migrations.AddField(
            model_name='reservation',
            name='guest',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
